version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install pipenv
      - pipenv shell
      - pipenv install -r requirements.txt

artifacts:
  files: '**/*'

post_build:
  commands:
    - cd app
    - uvicorn main:app --reload
